name: Code-Quality
on:
  workflow_dispatch:
  pull_request:


jobs:
  maven-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set up JDK 11
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
        with:
          maven-version: 3.9.0
      - name: mvn clean verify
        run: mvn clean verify
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package
      - name: Run doc check
        run: mvn org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:jar
      - name: Run spotless check
        run: mvn spotless:check
      - name: Check maven pom quality
        run: mvn org.kordamp.maven:pomchecker-maven-plugin:1.9.0:check-maven-central -D"checker.release=false"
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@7afb26c0c2f325c0d5c21ea1f617c79c7f899337 # v2022.3.4
      - uses: github/codeql-action/upload-sarif@b8d3b6e8af63cde30bdc382c0bc28114f4346c88 # v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
  generate-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set up JDK 11
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
        with:
          maven-version: 3.9.0
      - name: Generate code
        run: mvn clean package
      - name: mvn spotless:apply
        run: mvn spotless:apply
      - name: Check if code is generated
        run: git diff --exit-code src/main/java/ 
